micronaut:
  application:
    name: foo

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        dialect: H2
        hbm2ddl:
          auto: update